name: app_taxi_flutter
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_custom_clippers: ^2.1.0
  lottie: ^1.1.0
  firebase_auth: ^4.9.0
  firebase_core: ^2.15.1
  image_picker: ^1.0.4
  country_picker: ^2.0.21
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:

  uses-material-design: true

  assets:
     - assets/img/
     - assets/json/


    